token:
  secret:
    key: eyJhbGciOiJIUzI1NiJ9.ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0.ZEXseMCY36Z_ExBr6WkItx-4sENJOIOdizmHYE_J_Hs
  expiration: 3600

logging:
  level:
    root: INFO
  appenders:
    db:
      type: ch.qos.logback.classic.db.DBAppender
      connectionSource:
        type: ch.qos.logback.core.db.DriverManagerConnectionSource
        driverClass: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/redirecting_requests
        user: root
        password: root